status = [
    "fmt",
    "msrv",
    "msrv-workspace-crates (crates/rust-releases-channel-manifests)",
    "msrv-workspace-crates (crates/rust-releases-core)",
    "msrv-workspace-crates (crates/rust-releases-io)",
    "msrv-workspace-crates (crates/rust-releases-rust-changelog)",
    "msrv-workspace-crates (crates/rust-releases-rust-dist)",
    "msrv-workspace-crates (crates/rust-releases-rust-dist-with-cli)",
    "licenses_and_advisories (advisories)",
    "licenses_and_advisories (bans licenses sources)",
    "linter",
    "test (ubuntu-stable)",
    "test (macos-stable)",
    "test (win-gnu-stable)",
    "test (win-msvc-stable)",
    "test (ubuntu-beta)",
    "test (ubuntu-nightly)",
]

delete_merged_branches = true
