[licenses]
unlicensed = "deny"
copyleft = "deny"
confidence-threshold = 0.925
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unlicense",
    "Zlib",
    "OpenSSL",
    "Unicode-DFS-2016"
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c }
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"

ignore = [" RUSTSEC-2023-0052"]
