[package]
name = "rust-releases-core"
description = "Base traits and definitions for rust-releases"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
rust-version = "1.94"

[dependencies]
rust-release = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
yare = { workspace = true }
