use crate::error::GeneratorError;
use crate::tables::{self, Tables};
use rust_releases_core::rust_release::date::Date;
use rust_releases_core::{BetaReleases, NightlyReleases, StableReleases};
use std::fmt::Display;
use std::path::Path;

const MAX_CLIPPY_ARGUMENTS: usize = 7;

const HEADER: &str =
    "// Generated by 'cargo run -p rust-releases-bundled-generator'; do not edit by hand.\n\n";

const METADATA: &str = r#"use rust_releases_core::rust_release::date::Date;

pub fn generated_on() -> Date {
"#;

const STABLE_PROLOGUE: &str = r#"use crate::table::{Bundle, Tables};
use rust_releases_core::rust_release::date::Date;
use rust_releases_core::rust_release::toolchain::Channel;
use rust_releases_core::{RustRelease, Stable, StableReleases};

#[rustfmt::skip]
pub fn releases() -> StableReleases {
    let bundle = Bundle::new(&TABLES);

    RELEASES
        .iter()
        .map(|release| {
            let version = Stable::new(release.major, release.minor, release.patch);
            let release_date = Date::new(release.year, release.month, release.day);
            let channel = Channel::Stable(version.clone());

            RustRelease::new(
                version,
                Some(release_date.clone()),
                bundle.toolchains(&channel, &release_date, release.toolchains),
            )
        })
        .collect()
}

"#;

const BETA_PROLOGUE: &str = r#"use crate::table::{Bundle, Tables};
use rust_releases_core::rust_release::date::Date;
use rust_releases_core::rust_release::toolchain::Channel;
use rust_releases_core::{Beta, BetaReleases, RustRelease};

#[rustfmt::skip]
pub fn releases() -> BetaReleases {
    let bundle = Bundle::new(&TABLES);

    RELEASES
        .iter()
        .map(|release| {
            let version = Beta::new(
                release.major,
                release.minor,
                release.patch,
                release.prerelease,
            );
            let release_date = Date::new(release.year, release.month, release.day);
            let channel = Channel::Beta(version.clone());

            RustRelease::new(
                version,
                Some(release_date.clone()),
                bundle.toolchains(&channel, &release_date, release.toolchains),
            )
        })
        .collect()
}

"#;

const NIGHTLY_PROLOGUE: &str = r#"use crate::table::{Bundle, Tables};
use rust_releases_core::rust_release::date::Date;
use rust_releases_core::rust_release::toolchain::Channel;
use rust_releases_core::{Nightly, NightlyReleases, RustRelease};

#[rustfmt::skip]
pub fn releases() -> NightlyReleases {
    let bundle = Bundle::new(&TABLES);

    RELEASES
        .iter()
        .map(|release| {
            let version = Nightly::new(release.year, release.month, release.day);
            let release_date = Date::new(release.year, release.month, release.day);
            let channel = Channel::Nightly(version.clone());

            RustRelease::new(
                version,
                Some(release_date.clone()),
                bundle.toolchains(&channel, &release_date, release.toolchains),
            )
        })
        .collect()
}

"#;

const STABLE_FIELDS: &[(&str, &str)] = &[
    ("major", "u64"),
    ("minor", "u64"),
    ("patch", "u64"),
    ("year", "u16"),
    ("month", "u8"),
    ("day", "u8"),
    ("toolchains", "u32"),
];

const BETA_FIELDS: &[(&str, &str)] = &[
    ("major", "u64"),
    ("minor", "u64"),
    ("patch", "u64"),
    ("prerelease", "Option<u32>"),
    ("year", "u16"),
    ("month", "u8"),
    ("day", "u8"),
    ("toolchains", "u32"),
];

const NIGHTLY_FIELDS: &[(&str, &str)] = &[
    ("year", "u16"),
    ("month", "u8"),
    ("day", "u8"),
    ("toolchains", "u32"),
];

pub struct Written {
    pub entries: usize,
    pub changed: bool,
}

pub fn metadata(path: &Path, generated_on: &Date) -> Result<Written, GeneratorError> {
    let mut out = String::from(HEADER);

    out.push_str(METADATA);
    out.push_str(&format!("    {}\n}}\n", date(generated_on)));

    write(path, out, 1)
}

pub fn stable(path: &Path, releases: &StableReleases) -> Result<Written, GeneratorError> {
    let (tables, of_release) =
        tables::intern(releases.iter(), |version| version.version.to_string())?;

    let mut rows = String::new();

    for (release, toolchains) in releases.iter().zip(&of_release) {
        let version = release.version().version;
        let release_date = release_date(release.release_date(), &version)?;

        rows.push_str(&format!(
            "    Release::new({major}, {minor}, {patch}, {year}, {month}, {day}, {toolchains}),\n",
            major = version.major(),
            minor = version.minor(),
            patch = version.patch(),
            year = release_date.year(),
            month = release_date.month(),
            day = release_date.day(),
            toolchains = toolchains.0,
        ));
    }

    let mut out = String::from(HEADER);
    out.push_str(STABLE_PROLOGUE);
    out.push_str(&releases_table(STABLE_FIELDS, releases.len(), rows));
    out.push_str(&tables_of(&tables));

    write(path, out, releases.len())
}

pub fn beta(path: &Path, releases: &BetaReleases) -> Result<Written, GeneratorError> {
    let (tables, of_release) =
        tables::intern(releases.iter(), |version| version.version.to_string())?;

    let mut rows = String::new();

    for (release, toolchains) in releases.iter().zip(&of_release) {
        let version = release.version();
        let release_date = release_date(release.release_date(), &version.version)?;

        rows.push_str(&format!(
            "    Release::new({major}, {minor}, {patch}, {prerelease}, {year}, {month}, {day}, {toolchains}),\n",
            major = version.version.major(),
            minor = version.version.minor(),
            patch = version.version.patch(),
            prerelease = prerelease(version.prerelease),
            year = release_date.year(),
            month = release_date.month(),
            day = release_date.day(),
            toolchains = toolchains.0,
        ));
    }

    let mut out = String::from(HEADER);
    out.push_str(BETA_PROLOGUE);
    out.push_str(&releases_table(BETA_FIELDS, releases.len(), rows));
    out.push_str(&tables_of(&tables));

    write(path, out, releases.len())
}

pub fn nightly(path: &Path, releases: &NightlyReleases) -> Result<Written, GeneratorError> {
    let (tables, of_release) =
        tables::intern(releases.iter(), |version| version.date.ymd().to_string())?;

    let mut rows = String::new();

    for (release, toolchains) in releases.iter().zip(&of_release) {
        let release_date = &release.version().date;

        rows.push_str(&format!(
            "    Release::new({year}, {month}, {day}, {toolchains}),\n",
            year = release_date.year(),
            month = release_date.month(),
            day = release_date.day(),
            toolchains = toolchains.0,
        ));
    }

    let mut out = String::from(HEADER);
    out.push_str(NIGHTLY_PROLOGUE);
    out.push_str(&releases_table(NIGHTLY_FIELDS, releases.len(), rows));
    out.push_str(&tables_of(&tables));

    write(path, out, releases.len())
}

fn release_date<'a>(
    release_date: Option<&'a Date>,
    version: &impl Display,
) -> Result<&'a Date, GeneratorError> {
    release_date.ok_or_else(|| GeneratorError::UnknownReleaseDate {
        version: version.to_string(),
    })
}

// The rows of a release table are written as `Release::new(..)` rather than as a struct literal,
// because a literal per field prodice larger generated file sizes for little gain.
fn release_type(fields: &[(&str, &str)]) -> String {
    let mut out = String::from("struct Release {\n");

    for (name, ty) in fields {
        out.push_str(&format!("    {name}: {ty},\n"));
    }

    out.push_str("}\n\n");

    // clippy whines about more than 7 arguments, which some channels need :)
    if fields.len() > MAX_CLIPPY_ARGUMENTS {
        out.push_str("#[allow(clippy::too_many_arguments)]\n");
    }

    out.push_str("#[rustfmt::skip]\nimpl Release {\n    const fn new(");
    out.push_str(
        &fields
            .iter()
            .map(|(name, ty)| format!("{name}: {ty}"))
            .collect::<Vec<_>>()
            .join(", "),
    );
    out.push_str(") -> Self {\n        Self { ");
    out.push_str(
        &fields
            .iter()
            .map(|(name, _)| *name)
            .collect::<Vec<_>>()
            .join(", "),
    );
    out.push_str(" }\n    }\n}\n\n");

    out
}

fn releases_table(fields: &[(&str, &str)], len: usize, rows: String) -> String {
    format!(
        "{release}#[rustfmt::skip]\nstatic RELEASES: [Release; {len}] = [\n{rows}];\n\n",
        release = release_type(fields),
    )
}

fn tables_of(tables: &Tables) -> String {
    let mut out = String::from(
        r#"static TABLES: Tables = Tables {
    triples: &TRIPLES,
    components: &COMPONENTS,
    target_sets: &TARGET_SETS,
    component_sets: &COMPONENT_SETS,
    toolchains: &TOOLCHAINS,
    release_toolchains: &RELEASE_TOOLCHAINS,
};

"#,
    );

    out.push_str(&strings("TRIPLES", &tables.triples));
    out.push_str(&strings("COMPONENTS", &tables.components));
    out.push_str(&sets("TARGET_SETS", "u16", &tables.target_sets));
    out.push_str(&sets("COMPONENT_SETS", "u16", &tables.component_sets));
    out.push_str(&toolchains(&tables.toolchains));
    out.push_str(&sets(
        "RELEASE_TOOLCHAINS",
        "u32",
        &tables.release_toolchains,
    ));

    out
}

fn strings(name: &str, values: &[String]) -> String {
    let mut out = format!(
        "#[rustfmt::skip]\nstatic {name}: [&str; {len}] = [\n",
        len = values.len()
    );

    for value in values {
        out.push_str(&format!("    \"{value}\",\n"));
    }

    out.push_str("];\n\n");

    out
}

fn sets<T: Display>(name: &str, id: &str, values: &[Vec<T>]) -> String {
    let mut out = format!(
        "#[rustfmt::skip]\nstatic {name}: [&[{id}]; {len}] = [\n",
        len = values.len()
    );

    for value in values {
        out.push_str(&set(value));
    }

    out.push_str("];\n\n");

    out
}

fn set<T: Display>(ids: &[T]) -> String {
    let ids = ids.iter().map(|id| id.to_string()).collect::<Vec<_>>();

    let mut line = String::new();
    for id in ids {
        line.push_str(&format!("{id}, "));
    }

    if line.is_empty() {
        String::from("    &[],\n")
    } else {
        format!("    &[{line}],\n")
    }
}

fn toolchains(rows: &[(u16, u32, u32)]) -> String {
    let mut out = format!(
        "#[rustfmt::skip]\nstatic TOOLCHAINS: [(u16, u32, u32); {len}] = [\n",
        len = rows.len()
    );

    for (host, targets, components) in rows {
        out.push_str(&format!("    ({host}, {targets}, {components}),\n"));
    }

    out.push_str("];\n\n");

    out
}

fn date(date: &Date) -> String {
    format!(
        "Date::new({year}, {month}, {day})",
        year = date.year(),
        month = date.month(),
        day = date.day(),
    )
}

fn prerelease(prerelease: Option<u32>) -> String {
    match prerelease {
        Some(prerelease) => format!("Some({prerelease})"),
        None => "None".to_string(),
    }
}

fn write(path: &Path, content: String, entries: usize) -> Result<Written, GeneratorError> {
    let content = format!("{}\n", content.trim_end());

    let current = match std::fs::read_to_string(path) {
        Ok(current) => Some(current),
        Err(source) if source.kind() == std::io::ErrorKind::NotFound => None,
        Err(source) => {
            return Err(GeneratorError::Read {
                path: path.to_path_buf(),
                source,
            });
        }
    };

    if current.as_deref() == Some(content.as_str()) {
        return Ok(Written {
            entries,
            changed: false,
        });
    }

    std::fs::write(path, content).map_err(|source| GeneratorError::Write {
        path: path.to_path_buf(),
        source,
    })?;

    Ok(Written {
        entries,
        changed: true,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_a_date() {
        assert_eq!(date(&Date::new(2016, 3, 8)), "Date::new(2016, 3, 8)");
    }

    #[test]
    fn render_a_prerelease() {
        assert_eq!(prerelease(Some(3)), "Some(3)");
        assert_eq!(prerelease(None), "None");
    }

    #[test]
    fn render_an_empty_set() {
        assert_eq!(set::<u16>(&[]), "    &[],\n");
    }

    #[test]
    fn render_a_set() {
        assert_eq!(set(&[1u16, 2, 3]), "    &[1, 2, 3, ],\n");
    }
}
