use crate::error::GeneratorError;
use rust_releases_core::rust_release::date::Date;
use rust_releases_core::rust_release::toolchain::Target;
use rust_releases_core::{BetaReleases, NightlyReleases, RustRelease, Stable, StableReleases};
use std::collections::BTreeSet;
use std::path::Path;

const UNPARSABLE_TRIPLE: &str = "?";

const HEADER: &str =
    "// Generated by 'cargo run -p rust-releases-bundled-generator'; do not edit by hand.\n\n";

const METADATA: &str = r#"use rust_releases_core::rust_release::date::Date;

pub fn generated_on() -> Date {
"#;

const STABLE_PROLOGUE: &str = r#"use rust_releases_core::rust_release::date::Date;
use rust_releases_core::rust_release::toolchain::{Channel, Target, Toolchain};
use rust_releases_core::{RustRelease, Stable, StableReleases};
use std::collections::HashSet;

#[rustfmt::skip]
pub fn releases() -> StableReleases {
    let mut releases = StableReleases::empty();

"#;

const STABLE_EPILOGUE: &str = r#"
    releases
}

fn add(releases: &mut StableReleases, version: Stable, release_date: Date, hosts: &[&str]) {
    let toolchains = hosts
        .iter()
        .map(|host| {
            Toolchain::new(
                Channel::Stable(version.clone()),
                Some(release_date.clone()),
                Target::from_target_triple_or_unknown(host),
                HashSet::new(),
                HashSet::new(),
            )
        })
        .collect::<Vec<_>>();

    releases.add(RustRelease::new(version, Some(release_date), toolchains));
}
"#;

const BETA_PROLOGUE: &str = r#"use rust_releases_core::rust_release::date::Date;
use rust_releases_core::{Beta, BetaReleases, RustRelease};

#[rustfmt::skip]
pub fn releases() -> BetaReleases {
    let mut releases = BetaReleases::empty();

"#;

const BETA_EPILOGUE: &str = r#"
    releases
}

fn add(releases: &mut BetaReleases, version: Beta, release_date: Date) {
    releases.add(RustRelease::new(version, Some(release_date), []));
}
"#;

const NIGHTLY_PROLOGUE: &str = r#"use rust_releases_core::rust_release::date::Date;
use rust_releases_core::{Nightly, NightlyReleases, RustRelease};

#[rustfmt::skip]
pub fn releases() -> NightlyReleases {
    let mut releases = NightlyReleases::empty();

"#;

const NIGHTLY_EPILOGUE: &str = r#"
    releases
}

fn add(releases: &mut NightlyReleases, release_date: Date) {
    let version = Nightly {
        date: release_date.clone(),
    };

    releases.add(RustRelease::new(version, Some(release_date), []));
}
"#;

pub struct Written {
    pub entries: usize,
    pub changed: bool,
}

pub fn metadata(path: &Path, generated_on: &Date) -> Result<Written, GeneratorError> {
    let mut out = String::from(HEADER);

    out.push_str(METADATA);
    out.push_str(&format!("    {}\n}}\n", date(generated_on)));

    write(path, out, 1)
}

pub fn stable(path: &Path, releases: &StableReleases) -> Result<Written, GeneratorError> {
    let mut out = String::from(HEADER);
    out.push_str(STABLE_PROLOGUE);

    for release in releases.iter() {
        let version = release.version().version;
        let release_date =
            release
                .release_date()
                .ok_or_else(|| GeneratorError::UnknownReleaseDate {
                    version: version.to_string(),
                })?;

        out.push_str(&format!(
            "    add(&mut releases, Stable::new({major}, {minor}, {patch}), {date}, &[",
            major = version.major(),
            minor = version.minor(),
            patch = version.patch(),
            date = date(release_date),
        ));

        let hosts = hosts(release)?;

        if hosts.is_empty() {
            out.push_str("]);\n");
            continue;
        }

        out.push('\n');

        for host in &hosts {
            out.push_str(&format!("        \"{host}\",\n"));
        }

        out.push_str("    ]);\n");
    }

    out.push_str(STABLE_EPILOGUE);

    write(path, out, releases.len())
}

// A toolchain is bundled per host, so the hosts are what is rendered of it
fn hosts(release: &RustRelease<Stable>) -> Result<BTreeSet<String>, GeneratorError> {
    let unknown = Target::from_target_triple_or_unknown(UNPARSABLE_TRIPLE);

    release
        .toolchains_iter()
        .map(|toolchain| {
            let host = toolchain.host();

            if host == &unknown {
                return Err(GeneratorError::UnknownHost {
                    version: release.version().version.to_string(),
                });
            }

            Ok(host.to_string())
        })
        .collect()
}

pub fn beta(path: &Path, releases: &BetaReleases) -> Result<Written, GeneratorError> {
    let mut out = String::from(HEADER);
    out.push_str(BETA_PROLOGUE);

    for release in releases.iter() {
        let version = release.version();
        let release_date =
            release
                .release_date()
                .ok_or_else(|| GeneratorError::UnknownReleaseDate {
                    version: version.version.to_string(),
                })?;

        out.push_str(&format!(
            "    add(&mut releases, Beta::new({major}, {minor}, {patch}, {prerelease}), {date});\n",
            major = version.version.major(),
            minor = version.version.minor(),
            patch = version.version.patch(),
            prerelease = prerelease(version.prerelease),
            date = date(release_date),
        ));
    }

    out.push_str(BETA_EPILOGUE);

    write(path, out, releases.len())
}

pub fn nightly(path: &Path, releases: &NightlyReleases) -> Result<Written, GeneratorError> {
    let mut out = String::from(HEADER);
    out.push_str(NIGHTLY_PROLOGUE);

    for release in releases.iter() {
        out.push_str(&format!(
            "    add(&mut releases, {date});\n",
            date = date(&release.version().date)
        ));
    }

    out.push_str(NIGHTLY_EPILOGUE);

    write(path, out, releases.len())
}

fn date(date: &Date) -> String {
    format!(
        "Date::new({year}, {month}, {day})",
        year = date.year(),
        month = date.month(),
        day = date.day(),
    )
}

fn prerelease(prerelease: Option<u32>) -> String {
    match prerelease {
        Some(prerelease) => format!("Some({prerelease})"),
        None => "None".to_string(),
    }
}

fn write(path: &Path, content: String, entries: usize) -> Result<Written, GeneratorError> {
    let current = match std::fs::read_to_string(path) {
        Ok(current) => Some(current),
        Err(source) if source.kind() == std::io::ErrorKind::NotFound => None,
        Err(source) => {
            return Err(GeneratorError::Read {
                path: path.to_path_buf(),
                source,
            });
        }
    };

    if current.as_deref() == Some(content.as_str()) {
        return Ok(Written {
            entries,
            changed: false,
        });
    }

    std::fs::write(path, content).map_err(|source| GeneratorError::Write {
        path: path.to_path_buf(),
        source,
    })?;

    Ok(Written {
        entries,
        changed: true,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_a_date() {
        assert_eq!(date(&Date::new(2016, 3, 8)), "Date::new(2016, 3, 8)");
    }

    #[test]
    fn render_a_prerelease() {
        assert_eq!(prerelease(Some(3)), "Some(3)");
        assert_eq!(prerelease(None), "None");
    }
}
