[package]
name = "rust-release"
description = "Types to model a Rust release"
version = "3.0.0"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
rust-version = "1.94.1"

[dependencies]
rust-toolchain = { workspace = true }

[dev-dependencies]
yare = { workspace = true }
