[package]
name = "rust-releases-rust-changelog"
description = "RustChangelog source implementation for rust-releasess"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
rust-version = "1.92"

[dependencies]
time = { version = "0.3.7", features = ["macros", "parsing"] }
rust-releases-core = { workspace = true }
rust-releases-io = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
yare = "3.0.0"
