[package]
name = "rust-releases-bundled-generator"
description = "Generates the release data which is bundled by rust-releases-bundled"
version = "0.1.0"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
publish = false
rust-version = "1.94.1"

[dependencies]
rust-releases-core = { workspace = true }
rust-releases-io = { workspace = true, features = ["ureq"] }
rust-releases-rust-changelog = { version = "^0.33.0", path = "../rust-releases-rust-changelog" }
rust-releases-rust-dist = { version = "^0.33.0", path = "../rust-releases-rust-dist" }
rust-releases-bundled = { version = "^0.1.0", path = "../rust-releases-bundled", features = ["stable", "beta", "nightly"] }
thiserror = { workspace = true }
time = "0.3.47"

[dev-dependencies]
yare = { workspace = true }
